apiVersion: v1
kind: ConfigMap
metadata:
  name: taskapi-config
  labels:
    app: taskapi
data:
  NODE_ENV: "production"
  PORT: "3000"
  POSTGRES_DB: "taskapi"
  POSTGRES_USER: "taskapi"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
